### PR TITLE
add a load_data function to speed up loading the data

### PR DESCRIPTION
**Pull request by tlatorre-uchicago**
This commit adds a load_data function which saves a cache of the
dataframe to the ~/.cache/combine directory. This speeds up the initial
loading of the data by a huge amount.

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
Don't merge yet as I'm still testing it.

**Comment by tlatorre-uchicago** [comment]
Running the fit before:

```console
$ time ./runCombine.py -c high --skimmedTag _massHadTks_v4 -s histos
real    13m5.444s
user    10m41.226s
sys     1m51.292s
```

After:

```console
$ time ./runCombine.py -c high --skimmedTag _massHadTks_v4 -s histos
real    9m7.720s
user    7m37.602s
sys     1m30.252s
```

So saves about 4 minutes.

**Comment by tlatorre-uchicago** [comment]
Doh, actually I'm an idiot. I tested the "before" including the time it took to save to disk. Testing it again:

Before:

```console
$ time ./runCombine.py -c high --skimmedTag _massHadTks_v4 -s histos
real    8m52.287s
user    8m28.088s
sys     0m37.478s
```

After:

```console
$ time ./runCombine.py -c high --skimmedTag _massHadTks_v4 -s histos
real    6m35.530s
user    5m55.802s
sys     0m38.315s
```

So it still saves some time, but not a *huge* savings.

**Comment by ocerri** [comment]
Does this work also when you submit a job?

**Comment by tlatorre-uchicago** [comment]
No, it doesn't seem to work. I'm trying to figure out a way to elegantly do
that.

**Comment by tlatorre-uchicago** [comment]
Should work for condor jobs now

**Pull request merged**
